version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}         # Use environment variable from .env
      POSTGRES_USER: ${POSTGRES_USER}     # Use environment variable from .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Use environment variable from .env
    ports:
      - "5432:5432"                        # Expose the PostgreSQL port
    volumes:
      - pgdata:/var/lib/postgresql/data    # Persist data using a named volume

volumes:
  pgdata:
